### ISSUE TITLE
Add Tags and multiple environments to AWS deployment 

### ISSUE THREAD

**Issue by HasseNasse** [Hreem-IT/toggler#27]
```
Tags:
      - Key: "app"
        Value: "toggla"
      - Key: "region"
        Value: !Sub ${AWS::Region}
      - Key: "environment"
        Value: "test"
```
